<Project>
  <PropertyGroup>
    <Version>2.1.1</Version>
    <Authors>Rot contributors</Authors>
    <Product>Rot</Product>
    <Copyright>Copyright 2026 Rot contributors</Copyright>
    <RepositoryUrl>https://github.com/bkaranf/Rot</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
